Refactoring with pure bash
openSUSE/golang-packaging pull request #6
Opened 2016-12-22 13:39 UTC by tboerger

This PR shows the work of months to propery handle go packaging. It's already in use at home:tboerger:branches:devel:languages:go and should be submitted to devel:languages:go soon. To keep the history clean you should just squash the commits. /cc @monstermunchkin

2016-12-23 09:16 UTC, MaximilianMeister commented on CHANGELOG
> +    are also using fure bash and go tooling
`s/fure/pure`

2016-12-23 09:18 UTC, MaximilianMeister commented on golang.prov
> +# /home/abuild/rpmbuild/BUILDROOT/golang-github-codegangsta-cli-1.17.1+git20160828.599ee69-0.x86_64/usr/share/go/contrib/src/github.com/codegangsta/cli/altsrc
remainder of debugging or are the comments somehow necessary?

2016-12-23 09:19 UTC, MaximilianMeister commented on golang.prov
> +while read INPUT; do
I'd put a comment there to explain why we need to read from STDIN here

2016-12-23 09:36 UTC, MaximilianMeister commented on golang.prov
> +while read INPUT; do
also smells like endless loop in some cases? at least i had this during testing e.g. `golang-github-exercism-cli` where it gets stuck after `Finding  Requires: /usr/lib/rpm/golang.req`

2016-12-23 09:53 UTC, tboerger commented on golang.prov
> +# /home/abuild/rpmbuild/BUILDROOT/golang-github-codegangsta-cli-1.17.1+git20160828.599ee69-0.x86_64/usr/share/go/contrib/src/github.com/codegangsta/cli/altsrc
That's a reminder to see what gets piped in

2016-12-23 09:53 UTC, tboerger commented on golang.prov
> +while read INPUT; do
No endless loop, just takes sometimes a little bit longer

2016-12-23 10:57 UTC, MaximilianMeister commented on golang.prov
> +while read INPUT; do
right, it really took quite a while but it worked fine :+1:

2016-12-23 11:07 UTC, monstermunchkin requested changes

2016-12-23 11:07 UTC, monstermunchkin commented on golang.sh
> +  "armv3l"|"armv4b"|"armv4l"|"armv4tl"|"armv5b"|"armv5l"|"armv5teb"|"armv5tel"|"armv5tejl"|"armv6l"|"armv6hl"|"armv7l"|"armv7hl")
This can be shortened to `"armv*"`.

2016-12-23 11:07 UTC, monstermunchkin commented on golang.sh
> +    echo "Empty import path, please specify a valid one!"
This should be redirected to stderr.

2016-12-23 11:07 UTC, monstermunchkin commented on golang.sh
> +    echo "Please specify a valid importpath, refernce: go help test"
This should be redirected to stderr.

2016-12-23 11:07 UTC, monstermunchkin commented on golang.sh
> +    echo "Please specify a valid method: arch, prep, build, install, source, test, filelist, godoc"
This should be redirected to stderr.

2016-12-23 11:07 UTC, monstermunchkin commented on golang.sh
> +    rm -f ${file_list}
Unnecessary `if`-block since `rm -f` will not fail if the file is not present.

2017-01-16 09:27 UTC, tboerger commented
Do you want to merge this? Or should I close that?

2017-01-16 09:28 UTC, monstermunchkin commented
We'll merge it.

2017-01-24 12:32 UTC, monstermunchkin approved these changes

2017-01-24 12:40 UTC, jordimassaguerpla approved these changes

2017-02-15 15:48 UTC, merged

2017-02-15 20:15 UTC, tboerger commented
Yeah!